workflows:
  windows-to-ios-workflow:
    name: iOS Build (Windows Fix)
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: 1. Delete Corrupted Windows iOS Folder
        script: rm -rf ios
      - name: 2. Generate Fresh Mac iOS Folder
        script: flutter create .
      - name: 3. Install Dependencies
        script: flutter pub get
      - name: 4. Build iOS App
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa